name: CI 2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v1
    - name: Upload build for test runner
      uses: actions/upload-artifact@v1
      with:
        name: build-artifact
        path: ./

  test:
    runs-on: self-hosted
    needs: [build]
    
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: build-artifact
          path: ./

      - uses: php-actions/phpunit@v1
